### ISSUE TITLE
webhooks do not work on the Umbrel lnbits app

### ISSUE THREAD

**Issue by prbroadfoot** [lnbits/lnbits#167] opened 2021-04-05 22:50 UTC
When I create an invoice with a webhook using Umbrel's lnbits app, the webhook is never called and says "not sent yet" in the invoice description after the invoice has been paid. If I make a similar request but use lnbits.com, the webhook works as expected.

**Comment by steve-vincent** [comment] 2021-04-06 07:58
Same here. I actually just found this after reporting issue at Umbrel project (not sure where it belongs):
https://github.com/getumbrel/umbrel/issues/698

**Comment by fiatjaf** [comment] 2021-04-06 13:29
This is very hard to debug.
Can you get some logs?

**Comment by lukechilds** [comment] 2021-04-06 14:20
@fiatjaf FWIW we are on lnbits 8188ae0 in Umbrel.

https://github.com/getumbrel/umbrel/blob/ad755acb5212ecc9b503dd40482c680d9595af8b/apps/lnbits/docker-compose.yml#L11

Let us know if we need to update.

**Comment by steve-vincent** [comment] 2021-04-06 18:29
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]: [2021-04-06 18:27:30,788] ERROR in app: Exception on request GET /api/v1/payments/sse
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]: Traceback (most recent call last):
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 143, in handle_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     return await self.full_dispatch_request(request_context)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 165, in full_dispatch_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     result = await self.handle_user_exception(error)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 178, in handle_user_exception
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     return await super().handle_user_exception(error)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart/app.py", line 1076, in handle_user_exception
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     raise error
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 163, in full_dispatch_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     result = await self.dispatch_request(request_context)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart/app.py", line 1882, in dispatch_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     return await handler(**request_.view_args)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/app/lnbits/decorators.py", line 28, in wrapped_view
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     return await view(**kwargs)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/app/lnbits/core/views/api.py", line 272, in api_payments_sse
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     g.nursery.start_soon(payment_received)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 912, in start_soon
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     GLOBAL_RUN_CONTEXT.runner.spawn_impl(async_fn, args, self, name)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1357, in spawn_impl
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     raise RuntimeError("Nursery is closed to new arrivals")
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]: RuntimeError: Nursery is closed to new arrivals
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]: [2021-04-06 18:27:30 +0000] [17] [ERROR] Error in ASGI Framework
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]: Traceback (most recent call last):
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/hypercorn/trio/context.py", line 28, in _handle
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     await invoke_asgi(app, scope, receive, send)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/hypercorn/utils.py", line 219, in invoke_asgi
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     await app(scope, receive, send)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart/app.py", line 2068, in __call__
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     await self.asgi_app(scope, receive, send)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart/app.py", line 2091, in asgi_app
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     await asgi_handler(receive, send)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/asgi.py", line 18, in __call__
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     nursery.start_soon(self.handle_request, nursery, request, send)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 741, in __aexit__
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     raise combined_error_from_nursery
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/asgi.py", line 29, in handle_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     response = await self.app.handle_request(request)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 147, in handle_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     return await self.handle_exception(error)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart/app.py", line 1090, in handle_exception
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     raise error
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 143, in handle_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     return await self.full_dispatch_request(request_context)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 165, in full_dispatch_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     result = await self.handle_user_exception(error)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 178, in handle_user_exception
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     return await super().handle_user_exception(error)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart/app.py", line 1076, in handle_user_exception
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     raise error
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 163, in full_dispatch_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     result = await self.dispatch_request(request_context)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/quart/app.py", line 1882, in dispatch_request
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     return await handler(**request_.view_args)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/app/lnbits/decorators.py", line 28, in wrapped_view
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     return await view(**kwargs)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/app/lnbits/core/views/api.py", line 272, in api_payments_sse
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     g.nursery.start_soon(payment_received)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 912, in start_soon
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     GLOBAL_RUN_CONTEXT.runner.spawn_impl(async_fn, args, self, name)
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:   File "/opt/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1357, in spawn_impl
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]:     raise RuntimeError("Nursery is closed to new arrivals")
Apr  6 18:27:30 umbrel umbrel-app lnbits_web_1[734]: RuntimeError: Nursery is closed to new arrivals

**Comment by fiatjaf** [comment] 2021-04-06 19:28
Got it.

I think updating to `master` will fix a bunch of issues related to async Python stuff and SQLite that were plaguing us since always. This is one of them (although there are more).

@lukechilds

**Comment by lukechilds** [comment] 2021-04-23 14:05
This should be resolved in Umbrel v0.3.9.

@prbroadfoot @steve-vincent can you try updating and let us know if the issue is resolved?

**Comment by steve-vincent** [comment] 2021-04-24 08:26
Yes, thanks @lukechilds 

Updating to v0.3.9 resolved the issue

**Comment by lukechilds** [comment] 2021-04-24 13:11
Great!

@fiatjaf I think this issue can be closed.

**Closed** 2021-04-24 14:30 UTC

**Comment by qecez** [comment] 2021-07-30 12:33
I'm on Umbrel 0.3.14 and this just occured to me. The payment was received but the webhook is stuck on "not sent yet".
