### ISSUE TITLE
[BUG] Alby funding source in LNBits isn't set up properly

### ISSUE THREAD

**Issue by theroyalwhale** [lnbits/lnbits#2211] opened 2024-01-19 04:33 UTC
**Bug Description**
In the LNBits Admin panel, if you set Alby as your funding source, the value that Alby Wallet API returns will be considered msats while it's actually in sats.

**To Reproduce**
1. Open LNBits instance
2. Go to Admin panel
3. Set Alby as funding source
4. Put your access token
5. Save changes
6. "why do I have 0.012 sats"

**Expected behavior**
It should clearly be treated as sats instead of msats.

**Desktop (please complete the following information):**
- LNbits version: [Latest (I use official LNBits hosting)]
- Database [none]

**Additional context**
Nope.

**Comment by theroyalwhale** [comment] 2024-01-19 04:34
thanks people in the telegram! :)

**Comment by dni** [comment] 2024-01-22 07:52
is this issue resolved?

**Comment by dni** [comment] 2024-01-22 07:52
@bitkarrot  can you take a look at this?

**Comment by theroyalwhale** [comment] 2024-01-23 01:28
While waiting for this, my Legend LNBits wallet was hacked!
I do not have ANY idea how my user key leaked.
For reference, here is the invoice the hacker used: lnbc510u1pj6an6dsp5l7g8e3fnzv0x66hguvyy9xchwz3fqwmfaqp424dcyvlnlw7ydzmspp54293qafcfuske6qdczccfy9skf2srdddq7x5365e8tlk2qca7t2qdp27z0c02lsn7rmwg8sn7r6huyls7mjpuyls74lp8u8kuxqzjccqpjrzjqvtesvezx7wct8qdgw5serwd8eernw8qvudspfjhecujf4zf3um4gzl6ryqqfdgqqqqqqqlgqqqqqzsqyg9qxpqysgqrlf93e5qu66f3wpuk7qp6y5j439tak09sdjkc3j3wphl5aqna5nr9fathf2ggypmyu4myya8scvd58pa8n99pejaw4f5k8c2gsyq77gpeyy5mk

**Comment by bitkarrot** [comment] 2024-01-23 03:39
@dni ok i'll take a look at this on version 0.12 

not sure how legend can get hacked unless you accidentally pasted your link or admin keys somewhere visible.

**Comment by theroyalwhale** [comment] 2024-01-23 03:48
@bitkarrot i was using legend as a TEMPORARY funding source while this alby bug is being patched, i'm CERTAIN i NEVER shared the admin key / user key ANYWHERE AT ALL. perhaps one of the worse parts is that I know who the hacker is but I don't have PROOF it's him... >:(
It's entirely possible for him to try admin keys until he finds mine, isn't it?

**Comment by prusnak** [comment] 2024-01-23 04:45
> @bitkarrot i was using legend

Please do not discuss this in this unrelated issue. Github is not a support platform for legend.

**Comment by theroyalwhale** [comment] 2024-01-23 10:17
@prusnak Ok. When alby code fix tho?

**Comment by dni** [comment] 2024-01-23 10:32
working on it... takes a bit

**Comment by theroyalwhale** [comment] 2024-01-23 12:40
sure I understand, can't wait to use alby as funding source! tho I wonder why nobody found this bug before?

**Comment by theroyalwhale** [comment] 2024-01-24 03:10
When's next lnbits update fixing this?

**Comment by BrunswickBTC** [comment] 2024-01-25 03:16
I can confirm this issue is present in v0.11.3

**Comment by theroyalwhale** [comment] 2024-01-25 04:09
So when will v0.11.4 release?

**Comment by prusnak** [comment] 2024-01-25 04:15
> So when will v0.11.4 release?

There will be no 0.11.4 release. 

0.12.0 will be released once it is ready.

Also the issue is not fixed yet, so even if there was a release tomorrow, the fix would not be included.

**Comment by theroyalwhale** [comment] 2024-01-27 11:05
Is there a time estimate for 0.12.0 release?

**Comment by BrunswickBTC** [comment] 2024-01-27 16:07
You are welcome to submit a PR to fix this. Is this causing a problem in lnbits functionality other than the admin panel stated balance?

**Comment by prusnak** [comment] 2024-01-28 16:22
Fix in https://github.com/lnbits/lnbits/pull/2221

**Closed** 2024-02-06 08:26 UTC
Labels: bug
