### ISSUE TITLE
[BUG] Can't install lnbits on my MacOS with Python 3.11.1

### ISSUE THREAD

**Issue by LoadJulz** [lnbits/lnbits#2568] opened 2024-07-03 17:59 UTC
If I run poetry install --only main I get the following log:

`Installing dependencies from lock file

Package operations: 28 installs, 0 updates, 0 removals

  - Installing secp256k1 (0.14.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  0.29.2
  Using bundled libsecp256k1
  Traceback (most recent call last):
    File "/Users/julianbaumann/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/Users/julianbaumann/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/julianbaumann/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 271, in build_wheel
      return _build_backend().build_wheel(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/lz/t1dpdjjj5718xrcnhm_nnyv00000gn/T/tmpzzjf2zgn/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 415, in build_wheel
      return self._build_with_temp_dir(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/lz/t1dpdjjj5718xrcnhm_nnyv00000gn/T/tmpzzjf2zgn/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/lz/t1dpdjjj5718xrcnhm_nnyv00000gn/T/tmpzzjf2zgn/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/private/var/folders/lz/t1dpdjjj5718xrcnhm_nnyv00000gn/T/tmpzzjf2zgn/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 265, in <module>
    File "/private/var/folders/lz/t1dpdjjj5718xrcnhm_nnyv00000gn/T/tmpzzjf2zgn/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/lz/t1dpdjjj5718xrcnhm_nnyv00000gn/T/tmpzzjf2zgn/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 171, in setup
      ok = dist.parse_command_line()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/lz/t1dpdjjj5718xrcnhm_nnyv00000gn/T/tmpzzjf2zgn/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 478, in parse_command_line
      args = self._parse_command_opts(parser, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/lz/t1dpdjjj5718xrcnhm_nnyv00000gn/T/tmpzzjf2zgn/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 876, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/lz/t1dpdjjj5718xrcnhm_nnyv00000gn/T/tmpzzjf2zgn/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 543, in _parse_command_opts
      if not issubclass(cmd_class, Command):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: issubclass() arg 1 must be a class
  

  at ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with secp256k1 (0.14.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "secp256k1 (==0.14.0)"'.`

I already tried to run pip install wheel and also the recommended command in the error log.

Any ideas?

**Comment by prusnak** [comment] 2024-07-03 19:14
Works for me.

Do you have dev command line tools installed?

What does `xcode-select -p` say?

If it says `xcode-select: error: unable to get active developer directory...` then run

```
xcode-select --install
```

**Comment by LoadJulz** [comment] 2024-07-04 08:00
`xcode-select -p` is pointing to _/Applications/Xcode.app/Contents/Developer_

I also retried `xcode-select --install` and reinstalled it.

The issue stays the same. I get a ChefBuildError and can't install secp256k1.

**Comment by LoadJulz** [comment] 2024-07-04 08:40
Also tried it with Python 3.9 as written in the guide

**Comment by prusnak** [comment] 2024-07-04 11:26
How did you install poetry? Via brew? Are you on the latest?

**Comment by LoadJulz** [comment] 2024-07-04 14:24
I used the command `curl -sSL https://install.python-poetry.org | python3 -` as stated in the installation guide. Would it be better to install via Homebrew instead?

I’m currently on Poetry 1.8.3, but I’m not 100% sure if I installed it previously via Homebrew or another method. It might be a good idea to uninstall everything and start over. I’ll try this tomorrow.

Actually, I only want to debug a plugin and fix a bug there. Could I also accomplish this with a deployed version by linking an extension from a GitHub repository?

Could you recommend another method besides Poetry to get LnBits running locally for my case (since only Poetry is recommended)?

**Comment by LoadJulz** [comment] 2024-07-08 11:10
I am now using Docker. It is not 100% to develop with this because I always need to restart my container but it works and got my thing runnning that I needed 👍 

Should I close the issue?

**Comment by prusnak** [comment] 2024-07-08 11:16
> Should I close the issue?

Well, since we cannot reproduce the issue I would close it. If we could, I'd have left it open.

**Comment by dni** [comment] 2024-07-13 09:29
this is some kind of weird issue with poetry and ARM64 builds right now, its encounter in CI aswell and also for @motorina0 lets keep it open until resolved

**Comment by LoadJulz** [comment] 2024-07-14 20:34
I have a Intel x64 Mac

**Comment by dni** [comment] 2024-07-25 13:04
@LoadJulz  can you try again, the release build randomly start working again

**Comment by prusnak** [comment] 2024-07-27 17:34
> I’m currently on Poetry 1.8.3, but I’m not 100% sure if I installed it previously via Homebrew or another method.

FTR, I am on Poetry 1.8.3 installed from Homebrew (`brew install poetry`) and everything works just fine.

**Comment by bitkarrot** [comment] 2024-07-28 06:23
I'm on M1 OSX, installed poetry 1.8.3 using the [official installer](https://python-poetry.org/docs/#installing-with-the-official-installer), using python3.9.15 

@LoadJulz  I don't know if this would help 
I use [pyenv](https://github.com/pyenv/pyenv) to switch between versions of python,
as sometimes the default version of python on OSX doesn't jive too well, 
this tool helps ensures that `python` at the cli is the correct version 

running lnbits 0.12.10 ok.

**Closed** 2024-07-29 06:09 UTC
Labels: bug
