### ISSUE TITLE
Feature Request: add a list of user's created wallets to the homepage

### ISSUE THREAD

**Issue by javad94** [lnbits/lnbits#187] opened 2021-04-29 22:22 UTC
Hi, Thanks for your great service. I think there should be a list of wallets that users created on the homepage saved on the browser storage for each user, especially I can't see a caution note that if you don't save your wallet URL, your wallet will be gone.

**Comment by fiatjaf** [comment] 2021-04-30 00:06
Duplicate of https://github.com/lnbits/lnbits/issues/117.

**Closed by fiatjaf** 2021-04-30 00:06 UTC
