### ISSUE TITLE
[BUG] Payment failed, then ok, then pending. Sats never got returned to wallet after invoice expired.

### ISSUE THREAD

**Issue by ssurfertuga** [lnbits/lnbits#1976] opened 2023-09-28 20:26 UTC
**Describe the bug**
Hey guys, something strange happened to me a few days ago. I scanned an invoice with the web interface on my cell and got error 502. Next I used BlueWallet (connected to same LNbits wallet using LndHub) and the payment was marked as OK by BlueWallet.

However, the payment never went through (wallet balance shows that amount as withdrawn) and it stayed marked as pending on the web interface (<...>) and also in the database, in table apipayments. There's a row with that payment hash marked as pending [v].

Checking the node shows:
```
lncli trackpayment 195c2bad015dbd91f559ad750a9e3e6fc096b94fd419883b899a2793ca12eb41
[lncli] rpc error: code = NotFound desc = payment isn't initiated
```
So the payment never left the LN node.

**To Reproduce**
Can't reproduce as I don't know what happened to stop that payment going trough.

**Expected behavior**
I expect the sats to return to my wallet/balance and the transaction marked as failed after invoice expired.

**Screenshots**
<img width="1028" alt="Screenshot 2023-09-28 at 14 16 08" src="https://github.com/lnbits/lnbits/assets/8077390/9ef360a2-9a9c-496b-af92-bd47a4d4d036">
<img width="476" alt="Screenshot 2023-09-28 at 14 16 18" src="https://github.com/lnbits/lnbits/assets/8077390/5b4ab8f8-c2cb-4dc0-a1ec-679dae8cb937">
<img width="1148" alt="Screenshot 2023-09-28 at 14 16 45" src="https://github.com/lnbits/lnbits/assets/8077390/e8699b3f-ce43-443f-a1e3-3c836149b9c5">

**Desktop (please complete the following information):**
- LNbits version: 0.10.9
- Database: postgres

**Additional context**
I don't know if this is a bug or not. It could be a problem related to LndHub when it comes to BlueWallet acting as if the payment actually went through.
However, I expect the sats to be returned to my wallet and be shown in my balance after a pending invoice expires and the payment never got to leave the node.

**Comment by dni** [comment] 2024-06-03 07:11
hm, that previous message was kinda weird... is this issue resolved yet? i see its been a year since you reported it, we are now at `0.12.8`

**Comment by ssurfertuga** [comment] 2024-06-04 23:46
> hm, that previous message was kinda weird... is this issue resolved yet? i see its been a year since you reported it, we are now at `0.12.8`

Never got answered so not resolved for me. Any ideas?

**Comment by motorina0** [comment] 2024-07-30 07:59
We were not able to reproduce this issue and other users did not report it.
Closing it. Feel free to open it if it happens again.

**Closed by motorina0** 2024-07-30 07:59 UTC
Labels: bug
