### ISSUE TITLE
Problems with admin.macaroon for LNbits 0.9.4 with LND 0.15.2 on myNodeBTC 0.3.03

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits#1050] opened 2022-10-11 23:47 UTC
### Introduction

There are two problems notified in this report, with a workaround for one.  It seems there is an issue for LNbits presenting admin.macaroon information to lnd, sometimes, for some users, that can be worked around.  The problem is attributed to LNbits as the same information can be manually presented to lnd and it responds with success.

And, perhaps related, I have a rendering issue which I suspect is obvious to someone with more experience.

This repository seems the appropriate primary location as the issue is reported on distributions other than  @tehelsper's myNodeBTC, though it maybe of interest to that project as well.
### Description

After suffering a bit of difficulty (some due to my own actions) upgrading LNbits on myNodeBTC, the migration to a Dockerised version was complete but LNbits reported:

`Oct 11 15:22:11 myNode lnbits[12816]: 2022-10-11 02:22:11.69 | INFO | Retrying connection to backend in 5 seconds...`

While at the same time lnd reported:

`Oct 11 15:21:36 myNode lnd[27369]: 2022-10-11 15:21:36.484 [ERR] RPCS: [/lnrpc.Lightning/ChannelBalance]: cannot determine data format of binary-encoded macaroon`

Examining the `.env` configuration file showed no issues with the `LND_REST_MACAROON` value (which is regenerated every time the lnbits.service is invoked by a script at `/usr/bin/service_scripts/pre_lnbits.sh`.  It hex-encodes the value at `/mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/admin.macaroon` and the value was confirmed correct by hand on the cli)

Further confirmation of the correctness of the admin.macaroon encoding was obtained by performing, from within the Docker container:

```
$ MACAROON_HEADER="Grpc-Metadata-macaroon: $LND_REST_MACAROON"
$ curl -X GET --cacert /app/tls.cert --header "$MACAROON_HEADER" https://172.17.0.1:10080/v1/balance/channels 

{"balance":"4198", "pending_open_balance":"0", "local_balance":{"sat":"4198", "msat":"4198182"}, "remote_balance":{"sat":"1327", "msat":"1327818"}, "unsettled_local_balance":{"sat":"0", "msat":"0"}, "unsettled_remote_balance":{"sat":"0", "msat":"0"}, "pending_open_local_balance":{"sat":"0", "msat":"0"}, "pending_open_remote_balance":{"sat":"0", "msat":"0"}}
```

A workaround was offered on Telegram by Axel Hamburch, https://t.me/lnbits/48152 to replace the hex-encoded macaroon string with a path to the admin.macaroon file in `.env`

`LND_REST_MACAROON="/app/admin.macaroon"`

[Due to the operation of myNodeBTC and Docker, was necessary to modify the lnbits.service unit:

Comment out the call to insert the hex-encoded admin.macaroon in `.env`

```
# Use path to admin.macaroon and prevent pre_lnbits.sh from replacing it
# /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/admin.macaroon
# ExecStartPre=/usr/bin/service_scripts/pre_lnbits.sh

```
And make the admin.macaroon file available in the Docker container by adding this --volume option:

`--volume /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/admin.macaroon:/app/admin.macaroon`
]

This resulted in LNbits successfully connecting with the funding backend.

Unfortunately, one problem remains, the rendering of LNbits is very wrong:

![chrome_4A4bYdNv6m](https://user-images.githubusercontent.com/388061/195217331-2ee9be10-485d-42eb-9cbb-00e2a5676230.png)

**Comment by HamishMacEwan** [comment] 2022-10-13 01:42
After discovering that http://192.168.1.50:5000 worked correctly and some painstaking testing of schema, domains, and public and private IP addresses, I've discovered that `https_lnbits.conf`, or at least my modified version of it, is the culprit.  Mea culpa.

Having corrected that file to nearer match https://github.com/mynodebtc/mynode/blob/master/rootfs/standard/etc/nginx/sites-enabled/https_lnbits.conf the rendering problem has been eliminated.

I note though that two "quirks" remain:

1. The issue with hex-encoded macaroon
2. The host name used in the curl API examples.  Despite the invoking URL being https://, the examples are:

**Comment by callebtc** [comment] 2022-10-26 10:28
Hi @HamishMacEwan, can we still do anything about this?

**Comment by HamishMacEwan** [comment] 2022-10-31 18:48
Quirk 2 has been resolved by setting 

FORWARDED_ALLOW_IPS="*"

in .env.  The default was fine when the app wasn't inside a container, because the default was 127.0.0.1.  Once inside the container and in a Docker network, this failed and so forwarded headers from the reverse proxy weren't trusted and were ignored.

Or at least I think that's what was happening.

Quirk 1, the failure of hex encoded admin.macaroon remains, and I wonder, given how odd the error message is, if it isn't somehow related to containers and addressing, but no idea how.  Hex encoding seems like a solution which allows the requester to be on a different host from lnd, and that is essentially what the Docker container is, so how come the file path works and the hex version of its contents doesn't.

**Comment by muaawiyahtucker** [comment] 2022-11-02 15:15
Sorry, but I'm having trouble with the same thing, and I'm also having trouble following your advice.

What I did was (according to what you mentioned above),
1) In the  /usr/bin/service_scripts/pre_lnbits.sh file, I added a '#' before the part under the #Update env file so that it didn't do that any longer
2) In the .env file in /opt/mynode/lnbits/.env I changed the 
LND_REST_MACAROON="/app/admin.macaroon"
to
LND_REST_MACAROON="/mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/admin.macaroon"
3) The part about the dynode needing to add some volume code to the lnbits.service I have no idea what to do there.

Now it went from 
Oct 11 15:22:11 myNode lnbits[12816]: 2022-10-11 02:22:11.69 | INFO | Retrying connection to backend in 5 seconds...

to a boat load of errors, primarily that it cannot find /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/admin.macaroon.

If you can help me with this, as I can no longer use lnbits with mynode

**Comment by tehelsper** [comment] 2022-11-03 04:02
@muaawiyahtucker Can you try upgrading to the latest version? It has applied the workaround that avoid the issue with hex macaroons and sets up the docker volume mount to access the macaroon directly.

**Comment by tehelsper** [comment] 2022-11-03 04:04
Also, there is a small chance the hardcoded docker gateway IP address to access LND is not set properly. You may be running into this issue https://github.com/lnbits/lnbits/issues/1070 but it doesn't have a fix yet. It would be ideal to be able to specify the Docker gateway as a hostname so it automatically resolves.

**Comment by muaawiyahtucker** [comment] 2022-11-03 11:08
@tehelsper 
I am on the latest version of mynode and in that it's running 0.9.4 version of lnbits. I still get the error 

`Oct 11 15:22:11 myNode lnbits[12816]: 2022-10-11 02:22:11.69 | INFO | Retrying connection to backend in 5 seconds...`

When I try to access the lnbits via direct IP address, ie by clicking on the lnbits icon, the web browser says:

`"Safari can't connect to the server. Safari can't open the page "[node IP]:5000" because Safari can't connect to their server "[node IP]"."`

But when I change the port to 5001 (which is what the port should be from this [https://github.com/mynodebtc/mynode/blob/master/rootfs/standard/etc/nginx/sites-enabled/https_lnbits.conf](url)

I get this error

```
400 Bad Request

The plain HTTP request was sent to HTTPS port
nginx/1.14.2
```

Then I try it with https:// and then I get a warning that the connection is not private, that its not happy with the ssl certificate (which is just the mynode self signed one), and asking me if I want to proceed, which I do and then it says:

```
502 Bad Gateway

nginx/1.14.2
```

I'm at a loss here. Any help to get lnbits working on mynode would be really useful. It works fine on my Umbrel by the way.

**Comment by tehelsper** [comment] 2022-11-04 03:16
Yeah, when I referred to the IP I was talking about within the lnbits config file. I'm not yet sure why the connections are failing  on a number of systems.

**Comment by muaawiyahtucker** [comment] 2022-11-13 15:32
@tehelsper 
MyNode recently updated their node, but this issue still persists. Any ideas so far since we last spoke?

**Comment by callebtc** [comment] 2022-11-13 15:38
The rendering issue is probably unrelated and might be because mynode didn't build the static files upon Installation. Can you run `build.py` in your lnbits folder to see if it fixes your issue?

**Comment by muaawiyahtucker** [comment] 2022-11-14 17:04
> The rendering issue is probably unrelated and might be because mynode didn't build the static files upon Installation. Can you run `build.py` in your lnbits folder to see if it fixes your issue?

Sorry to be thick, but there is no such file in the lnbits folder. There are only files that begin with 'ext' and end with '.sqlite3'.

I think lnbits is running on a docker.

**Comment by tehelsper** [comment] 2022-11-15 03:59
It does run in an LND container. The errors you saw are from NGINX in myNode and not LNBits. Those appear for any app is the backend app is not running properly.

You could try re-installing lnbits. Do you have a custom lnd config?

**Comment by muaawiyahtucker** [comment] 2022-11-15 17:12
> It does run in an LND container. The errors you saw are from NGINX in myNode and not LNBits. Those appear for any app is the backend app is not running properly.
> 
> You could try re-installing lnbits. Do you have a custom lnd config?

No, I don't. I have nothing custom about my node besides adding tailscale. Everything is as it was 'out of the box'. I've tried reinstalling lnBits. But I don't think I've totally deleted it and re-added it...as I wasn't sure what would happen to the accounts I currently have on them.

**Comment by muaawiyahtucker** [comment] 2022-12-29 00:55
> It does run in an LND container. The errors you saw are from NGINX in myNode and not LNBits. Those appear for any app is the backend app is not running properly.
> 
> You could try re-installing lnbits. Do you have a custom lnd config?

I've kinda found something interesting.

I loaded up LNBits on a VPS using docker, and when I tried to connect it to my MyNode, the exact same error above occurs with the exact same error message of 

`Retrying connection to backend in 5 seconds...`

I put the macaroon and IP to my Umbrel and it worked fine. So for some reason, the macaroon and IP address:port to myNode just doesn't work even from an external source...BUT...My Zeus wallet connects fine to it. I put the exact same port, IP and macaroon into Zeus and it works but just not on LNBits. Any ideas?

**Comment by tehelsper** [comment] 2022-12-29 01:40
Zeus does allow you to skip certificate verification. Could it be that LNBits is trying to validate the certificate and that's stopping the connection?

You could try to regenerate the TLS cert in mynode and re-attempt the connection.

**Comment by muaawiyahtucker** [comment] 2022-12-29 14:13
> Zeus does allow you to skip certificate verification. Could it be that LNBits is trying to validate the certificate and that's stopping the connection?
> 
> You could try to regenerate the TLS cert in mynode and re-attempt the connection.

Tried that, put the .cert onto the server, pointed it to the certificate on LNBits and still I just get
`2022-12-29 14:11:23.03 | INFO | Retrying connection to backend in 5 seconds...`

**Comment by muaawiyahtucker** [comment] 2022-12-29 15:20
> Zeus does allow you to skip certificate verification. Could it be that LNBits is trying to validate the certificate and that's stopping the connection?
> 
> You could try to regenerate the TLS cert in mynode and re-attempt the connection.

FINALLY!!!!!!

SOLVED IT!!

Phew!! I was going mad with this one.

So here's what I did.

Step 1: Downloaded the TLS certificate and admin Macaroon
Step 2: Uploaded both on my VPS server in a given location
Step 3: As I was using LNBits as a docker image, I had to map the location of the two files to their location on the VPS. I initially just put the location of the files in the .env file but then I kept on getting the error that the files didn't exist. I never got that error when I just pointed to the TLS certificate, but when I did the same with the macaroon i did.
Step 4: Re-create the docker image with that mapping in the .env. The .env pointed to the location inside the docker, and the then the docker itself mapped to the external location. It's very important not to confuse the two locations. I used a simple /app/tls.cert and /app/admin.macaroon as the location in the .env and the mapping to the external in the initial build. So the instructions on [https://github.com/lnbits/lnbits/blob/main/docs/guide/installation.md](url) on option 4, it has:

`docker run --detach --publish 5000:5000 --name lnbits-legend --volume ${PWD}/.env:/app/.env --volume ${PWD}/data/:/app/data lnbits-legend`

so I guess you could adjust it to the following:
`docker run --detach --publish 5000:5000 --name lnbits-legend --volume ${PWD}/.env:/app/.env --volume ${PWD}/data/:/app/data --volume [location on your system of certificate]/tls.cert:/app/tls.cert [location on your system of certificate]/admin.macaroon:/app/admin.macaroon lnbits-legend`

I'm guessing thats the code, I built it using a docker management software so I haven't verified this via command line.

Then everything should work

**Summary and Conclusion**
The reason why it worked on my umbrel is because i didn't use a tls certificate and because I literally pasted the HEX of the macaroon into the .env file. The reason why MyNode also works on Zeus is because of the same reason, thats what gave me the hint.
So the error is caused by lnbits unable to find the TLS and macaroon from within the docker (which was the issue I had). As for why it's not working on MyNode itself, I don't know. I've only managed to get it working from my VPS. I'm not sure how it all works on MyNode, so not sure if anyone could give me the heads up on how to fix it there, if they know how LNBits works on mynode.

**Comment by muaawiyahtucker** [comment] 2022-12-29 15:32
> The rendering issue is probably unrelated and might be because mynode didn't build the static files upon Installation. Can you run `build.py` in your lnbits folder to see if it fixes your issue?

Can you help me run the lnbits docker image with the parameters as stated in the first post. I know how to do it on my VPS, but I don't know how to do it on the MyNode. I think if I could do that I would be able to fix this persistent problem

**Comment by tehelsper** [comment] 2022-12-29 15:40
It should do that automatically. It volume-mounts the tls cert and admin macaroon files

> --volume /mnt/hdd/mynode/lnd/tls.cert:/app/tls.cert \
> --volume /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/admin.macaroon:/app/admin.macaroon \

**Comment by muaawiyahtucker** [comment] 2023-01-28 10:42
Whatever the problem was, it has since been fixed by the latest update for mynode...Thank you all for your help.

**Comment by dni** [comment] 2023-06-25 22:01
closing this, we are at lnbits `0.10.9` now.

**Closed by dni** 2023-06-25 22:01 UTC
