### ISSUE TITLE
Bug in satspay/display.html

### ISSUE THREAD

**Issue by dadofsambonzuki** [lnbits/lnbits#1012] opened 2022-09-27 20:50 UTC
There is a bug in Satspay when using Tip Jar where a `404 - wallet does not exist` error pops up at the bottom of the screen, even though the wallets are connected and the payment does complete.

[Potential fix from iWarpBTC here](https://github.com/iWarpBTC/lnbits-legend/blob/5f8884f6973ac55e1dbbb546fc31611273d785bc/lnbits/extensions/satspay/templates/satspay/display.html)

**Comment by TrezorHannes** [comment] 2022-10-04 18:35
This is how the error looks like. Payment goes through, but donaters refrain from donating since they think the sats will go awol 😢 
![image](https://user-images.githubusercontent.com/35168804/193898131-4f23e069-6647-4e33-8d5e-c5e3cd6d5d12.png)

**Comment by blackcoffeexbt** [comment] 2022-10-25 10:37
This issue has been resolved. I can't find the commit hash for the fix but I have experienced the same in the past. Ben mentioned that this has been fixed and I can't reproduce this issue so closing the issue. Thanks @dadofsambonzuki

**Closed by blackcoffeexbt** 2022-10-25 10:37 UTC
