### ISSUE TITLE
[BUG] Trying to pay already used LN invoice: 500 Internal Server Error

### ISSUE THREAD

**Issue by andrejpekarcik** [lnbits/lnbits#1425] opened 2023-01-27 13:26 UTC
**Describe the bug**
I paste the LN invoice (outbound payment), click Pay and invoice is correctly processed and payed. I paste once more the same invoice and I get 500 Internal Server Error.

**To Reproduce**
1. Go to your lnbits wallet.
2. Click on PASTE REQUEST and paste your LN invoice
3. Click READ then PAY
4. LN invoice is payed
5. Click PASTE REQUEST and paste the same LN invoice
6. Click READ then PAY
7. 500 Internal Server Error

**Expected behavior**
I expected message 'LN invoice is already paid'

**Screenshots**
![Captura desde 2023-01-27 14-04-44](https://user-images.githubusercontent.com/11619221/215097189-a32060b2-423c-4f18-b671-5b98c814f8c1.png)

**Additional context**
https://legend.lnbits.com exhibits same bug. Commit version: 45a0657828f2dc2bd772c57a20af4df5670c4ee6

**Comment by dni** [comment] 2023-03-28 21:08
can confirm the issue, paying an external invoice twice.
![screenshot-1680037635](https://user-images.githubusercontent.com/1743657/228367162-3a1521ae-cc9c-4322-b1bd-d956f23b19ce.jpg)

**Comment by dni** [comment] 2023-03-28 21:34
i think the issue is resolved in those to PRs i have open linked to this issue, hopefully merged soon :) thanks for creating an issue!

**Closed by dni** 2023-03-28 21:34 UTC
Labels: bug
