### ISSUE TITLE
[BUG] Lightning Addresses no longer work

### ISSUE THREAD

**Issue by tiker** [lnbits/lnbits#2540] opened 2024-05-29 20:24 UTC
**Describe the bug**
LN Addresses do not appear to be functional now.  I noticed a problem with 0.12.6 and just updated to 0.12.8 but still doesn't seem to work.  I have had the LNURLP extension loaded and configured for quite a while, receiving payments to my account but it stopped working with one of the recent updates.

**To Reproduce**
I created a test account on https://demo.lnbits.com to verify that it is not isolated to my node.

1. I have created a test account - https://demo.lnbits.com/wallet?usr=3c8518c4915b4699a0bb0ee677c3876a
2. Enabled the LNURLP (Pay Links) extension
3. Created a new payment link with the address "test123@demo.lnbits.com"
4. Viewing https://demo.lnbits.com/.well-known/lnurlp/test123 returns a JSON document with "address not found".
5. LN decoder pages such as https://lightningdecoder.com/test123@demo.lnbits.com also report the same error.

**Expected behavior**
The expected behavior would be a valid response with payment details?  (Not sure what the correct wording is.)  The functionality that used to work.

**Additional context**
The account linked above is a test account for this issue.  Feel free to play around with it, use it for troubleshooting, delete it if you like, whatever.

**Comment by bitkarrot** [comment] 2024-07-28 05:58
Payments to Lightning addresses appear to be working on https://demo.lnbits.com which is currently running

 LNBits **0.12.9** and Pay links extension version 0.5.0  as of Sun Jul 28 05:51:52 UTC 2024

Tested: 
1.  https://demo.lnbits.com/lnurlp/link/bRRLRy
2.  bitkarrot@demo.lnbits.com 
<img width="495" alt="Screenshot 2024-07-27 at 10 58 15 PM" src="https://github.com/user-attachments/assets/50795f8b-6325-46a4-b17f-8435d9f7cd49">



Note: lnbits v0.12.6 does not work with Pay links 0.5.0 as noted by OP.

**Comment by prusnak** [comment] 2024-07-28 07:15
Thanks for testing

Closing

**Comment by prusnak** [comment] 2024-07-30 14:31
> I'm not sure what test was performed but this issue is not fixed.

Are you on the latest LNbits version?

**Comment by tiker** [comment] 2024-07-30 14:34
This is sending to the official demo instance (demo.lnbits.com) which @bitkarrot claims works.

**Comment by prusnak** [comment] 2024-07-30 14:37
@bitkarrot did you remove the alias `bitkarrot@demo.lnbits.com` after testing?

**Comment by tiker** [comment] 2024-07-30 14:40
My tests address was not removed and still does not work.
![image](https://github.com/user-attachments/assets/73a652b9-9bcb-4f11-85b8-5f23997ae48c)

**Comment by bitkarrot** [comment] 2024-07-30 17:52
@prusnak just retested, as of : Tue Jul 30 17:52:44 UTC 2024

LN Address is still there, it was working on sunday, does not seem to be working now. however LNURL is definitely working.

**Comment by bitkarrot** [comment] 2024-07-30 18:30
see test video here  as of : Tue Jul 30 17:52:44 UTC 2024


https://github.com/user-attachments/assets/e6650537-2af6-4d98-b5c2-e80b9daa9b1e

**Comment by bitkarrot** [comment] 2024-07-30 20:33
Oddly, https://sendsats.to/bitkarrot@demo.lnbits.com

<img width="719" alt="Screenshot 2024-07-30 at 1 32 38 PM" src="https://github.com/user-attachments/assets/977dbeca-db1a-4231-ac24-a2de2c773180">

**Comment by motorina0** [comment] 2024-07-31 13:36
I believe the issue is caused by a conflict between `lnaddress` and `lnurlp` in mapping the same route:

- lunrlp: https://github.com/lnbits/lnurlp/blob/main/__init__.py#L20
- lnaddress: https://github.com/lnbits/lnaddress/blob/main/__init__.py#L21

There is no deterministic way in which the extensions are loaded, therefore the unpredictable behavior.

Suggestion: remove `lnaddress` from demo server since.

**Comment by motorina0** [comment] 2024-07-31 14:00
`lnaddress` deactivated on demo. Everyone can pay @bitkarrot now.

![telegram-cloud-photo-size-4-5859294209289339647-y](https://github.com/user-attachments/assets/8ba5e993-6cdc-4f2c-9a22-e6b3f49c7db8)

Closing issue. Please re-open if you are still experiencing issues.

**Comment by tiker** [comment] 2024-07-31 14:09
I can confirm, this fixed my issue on my own server.  This could be an issue for others also running both extensions together.  Should something be put in place to prevent both extensions from loading together causing this behavior?

**Comment by motorina0** [comment] 2024-08-01 07:02
> I can confirm, this fixed my issue on my own server. This could be an issue for others also running both extensions together. Should something be put in place to prevent both extensions from loading together causing this behavior?

You are right. Re-opining the issue and assigning it to me.

**Comment by prusnak** [comment] 2024-08-01 13:23
> Re-opining the issue and assigning it to me.

How do you plan to fix the issue? Is there a possibility to assign priorities to redirect paths? Or we just create a new mechanism that allows to mark two extensions as incompatible with each other?

**Comment by bitcointwente** [comment] 2024-08-03 20:51
I can confirm that on my 0.12.10 instance Paylinks did not work until I removed / disabled the LNAddress extension completely. I did not have it configured, just enabled.

I also had to restart the server after this.

**Closed** 2024-09-11 14:14 UTC
Labels: bug
