### ISSUE TITLE
Unsupported upgrade request nginx/Uvicorn [BUG]

### ISSUE THREAD

**Issue by dharake** [lnbits/lnbits#1647] opened 2023-04-24 00:55 UTC
When running LNbits with Nginx as a reverse proxy, you receive "Unsupported upgrade request" in LNBits log.

After many many hours of fiddling, I've understood the problem, but not sure how to resolve it.

In my nginx location block, I have the following:

        location / {
                proxy_pass http://127.0.0.1:5000; # This is your uvicorn LNbits local host IP and port
                proxy_set_header Upgrade $http_upgrade;
               # proxy_set_header Connection 'upgrade';
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header Host $host;
                proxy_http_version 1.1; # headers to ensure replies are coming back and forth through your domain
       }

The line commented out is the culprit. However if you remove it then you are not able to connect to Nostr Relays with LNBits Nostr Relay Extension. 

Further reading over here https://github.com/tiangolo/fastapi/discussions/7166 suggests that Uvicorn needs to be reinstalled with a different version. However having used the poetry method of installation for LNBits, I have no idea how to do this. Any guidance is much appreciated.

**Comment by dharake** [comment] 2023-04-25 00:50
*Solved*

I found the solution. In your nginx configuration file replace `proxy_set_header Connection 'upgrade';` wtih `proxy_set_header Connection    $connection_upgrade;` and then update /etc/nginx/nginx.conf with following in http block:

`http {  
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        …

        ##
        # Connection header for WebSocket reverse proxy
        ##
+       map $http_upgrade $connection_upgrade {
+           default upgrade;
+           ''      close;
+       }

        # further configurations …
}`

Restart nginx and LNBits.

**Comment by svacinaSSAI** [comment] 2023-05-14 14:41
Hi, I have the same problem but your solution didn't help me. I edited both configuration files but still the same message. Wasn't there another catch?

Thanks for the reply,

**Comment by dharake** [comment] 2023-05-14 14:53
I'll get back to you in the next few hours @svacinaSSAI

**Comment by believethehype** [comment] 2023-06-25 17:05
Same here. I also cant create invoices because of this issue. worked with older versions but still not sure how to make it work again.

**Comment by motorina0** [comment] 2024-07-30 11:33
Closing issue as the OP is solved.
Please open a new one with your own details if it still reproduces.

**Closed by motorina0** 2024-07-30 11:33 UTC
Labels: bug
